export const linkedinSelectors = {
  login: {
    emailInput: '#username, input[name="session_key"]',
    passwordInput: '#password, input[name="session_password"]',
    loginButton: '.btn__primary--large, button[type="submit"]',
    loginForm: '#login-form, form[data-test-login-form]',
    forgotPassword: 'a[data-test-forgot-password], .forgot-password a',
    signUp: 'a[data-test-registration-link], .register-link a',
    captcha: '#captcha-challenge, .captcha-container',
    twoFactorInput: '#input__phone_verification_pin, input[name="pin"]',
    twoFactorSubmit: 'button[data-test-two-factor-submit]',
    rememberMe: '#rememberMeOptIn, input[name="rememberMeOptIn"]',
  },

  navigation: {
    jobsTab: 'a[href*="/jobs/"], nav a[data-test-jobs-nav]',
    feedTab: 'a[href*="/feed/"], nav a[data-test-feed-nav]',
    myNetworkTab: 'a[href*="/mynetwork/"], nav a[data-test-mynetwork-nav]',
    messagingTab: 'a[href*="/messaging/"], nav a[data-test-messaging-nav]',
    notificationsTab: 'a[href*="/notifications/"], nav a[data-test-notifications-nav]',
    profileMenu: '.global-nav__me, [data-test-profile-menu]',
    logoutButton: 'a[data-test-sign-out], .sign-out-link',
  },

  jobSearch: {
    searchInput: 'input[placeholder*="Search"], .jobs-search-box__text-input',
    locationInput: 'input[placeholder*="Location"], .jobs-search-box__location-input',
    searchButton: 'button[aria-label="Search"], .jobs-search-box__submit-button',
    filtersButton: 'button[aria-label="Filters"], .search-reusables__filter-button',
    remoteFilter: 'label[for*="remote"], input[value="2"]',
    experienceFilter: '.search-reusables__filter-pill-button',
    datePostedFilter: 'button[aria-label*="Date posted"]',
    sortBy: 'select[aria-label*="Sort"], button[aria-label*="Sort"]',
    jobCardsContainer: '.jobs-search-results__list, .scaffold-layout__list',
    jobCard: '.job-card-container, .jobs-search-results__list-item, .job-card-list__entity-lockup',
    jobCardLink: 'a.job-card-list__title, .job-card-container__link',
    jobTitle: '.job-card-list__title, h3 a, .artdeco-entity-lockup__title a',
    companyName: '.job-card-container__company-name, .artdeco-entity-lockup__subtitle',
    location: '.job-card-container__metadata-item, .artdeco-entity-lockup__caption',
    postedDate: '.job-card-container__posted-date, time',
    salary: '.job-card-container__salary-info, .salary-info',
    easyApplyBadge: '.job-card-container__easy-apply-label, .easy-apply-badge',
    promotedBadge: '.job-card-container__promoted-label',
    pagination: '.artdeco-pagination',
    nextPage: 'button[aria-label="Next"], .artdeco-pagination__button--next',
    previousPage: 'button[aria-label="Previous"], .artdeco-pagination__button--previous',
    resultsCount: '.jobs-search-results__list-header, .display-flex.t-12',
    noResults: '.jobs-search-no-results, .no-results',
    loadingSpinner: '.artdeco-spinner, .jobs-search-results__list-loader',
  },

  jobDetail: {
    container: '.jobs-details-top-card, .job-view-layout',
    title: '.job-details-jobs-unified-top-card__job-title, h1.t-24',
    companyName: '.job-details-jobs-unified-top-card__company-name a, .job-details-jobs-unified-top-card__company-name',
    location: '.job-details-jobs-unified-top-card__bullet, .tvm__text--low-emphasis',
    description: '.jobs-description__content, .jobs-box__html-content',
    descriptionText: '.jobs-description__content .jobs-box__html-content, .jobs-description-content__text',
    requirements: '.jobs-description__content li, .jobs-box__html-content li',
    responsibilities: '.jobs-description__content li, .jobs-box__html-content li',
    benefits: '.jobs-benefits__list li, .benefits-list li',
    applyButton: '.jobs-apply-button, button.jobs-apply-button, button:has-text("Easy Apply"), button:has-text("Apply")',
    saveButton: 'button[aria-label*="Save"], .jobs-save-button',
    shareButton: 'button[aria-label*="Share"], .jobs-share-button',
    companyLink: '.job-details-jobs-unified-top-card__company-name a',
    companySize: '.job-details-jobs-unified-top-card__company-info span',
    industry: '.job-details-jobs-unified-top-card__company-info span:nth-child(2)',
    postedDate: '.job-details-jobs-unified-top-card__posted-date, time',
    applicantCount: '.job-details-jobs-unified-top-card__applicant-count',
    jobFunction: '.job-details-jobs-unified-top-card__job-functions',
    seniorityLevel: '.job-details-jobs-unified-top-card__seniority-level',
    employmentType: '.job-details-jobs-unified-top-card__employment-type',
    jobId: '[data-job-id], .jobs-unified-top-card__job-id',
    similarJobs: '.jobs-recommendations__list, .similar-jobs',
  },

  easyApply: {
    modal: '.jobs-easy-apply-modal, [role="dialog"][aria-label*="Easy Apply"]',
    modalContent: '.jobs-easy-apply-content, .artdeco-modal__content',
    nextButton: 'button[aria-label="Continue to next step"], button:has-text("Next"), .artdeco-button--primary',
    reviewButton: 'button[aria-label="Review your application"], button:has-text("Review")',
    submitButton: 'button[aria-label="Submit application"], button:has-text("Submit"), .artdeco-button--primary',
    backButton: 'button[aria-label="Go back"], button:has-text("Back")',
    closeButton: 'button[aria-label="Dismiss"], .artdeco-modal__dismiss',
    fileUpload: 'input[type="file"], .jobs-document-upload__file-input',
    fileUploadLabel: '.jobs-document-upload__label, label[for*="resume"]',
    phoneInput: 'input[name="phoneNumber"], input[id*="phone"]',
    emailInput: 'input[name="email"], input[id*="email"]',
    coverLetterTextarea: 'textarea[name="coverLetter"], textarea[id*="coverLetter"]',
    coverLetterLabel: 'label:has-text("Cover letter")',
    linkedInProfileInput: 'input[name="profileUrl"], input[id*="profile"]',
    portfolioUrlInput: 'input[name="portfolioUrl"], input[id*="portfolio"]',
    githubUrlInput: 'input[name="githubUrl"], input[id*="github"]',
    questionContainer: '.jobs-easy-apply-form-section__grouping, .fb-dash-form-element',
    questionLabel: 'label, .fb-dash-form-element__label',
    questionInput: 'input, textarea, select',
    radioGroup: '.fb-dash-form-element__radio-group, fieldset',
    radioOption: 'input[type="radio"], .fb-dash-form-element__radio-option',
    checkboxGroup: '.fb-dash-form-element__checkbox-group',
    checkboxOption: 'input[type="checkbox"]',
    selectDropdown: 'select, .artdeco-select',
    selectOption: 'option',
    errorMessage: '.artdeco-inline-feedback--error, .fb-dash-form-element__error',
    requiredIndicator: '.fb-dash-form-element__required, [aria-required="true"]',
    stepIndicator: '.jobs-easy-apply-footer__step-indicator, .artdeco-stepper__step',
    currentStep: '.jobs-easy-apply-footer__step-indicator--current, .artdeco-stepper__step--active',
    completedSteps: '.artdeco-stepper__step--completed',
    progressBar: '.jobs-easy-apply-footer__progress-bar, .artdeco-progress-indicator',
    confirmationModal: '.artdeco-modal[aria-label*="Application submitted"], .jobs-easy-apply-confirmation',
    confirmationMessage: '.artdeco-modal__content h2, .jobs-easy-apply-confirmation__message',
    doneButton: 'button[aria-label="Done"], button:has-text("Done")',
    discardButton: 'button[aria-label="Discard"], button:has-text("Discard")',
  },

  profile: {
    profileUrl: '.global-nav__me-photo, a[href*="/in/"]',
    name: '.pv-text-details__left-panel h1, .profile-name',
    headline: '.pv-text-details__left-panel .text-body-medium, .profile-headline',
    location: '.pv-text-details__left-panel .text-body-small, .profile-location',
    about: '.pv-about-section .pv-shared-text-with-see-more, .about-section',
    experience: '.pv-profile-section.experience-section, #experience',
    education: '.pv-profile-section.education-section, #education',
    skills: '.pv-profile-section.skills-section, #skills',
    certifications: '.pv-profile-section.certifications-section, #certifications',
    projects: '.pv-profile-section.projects-section, #projects',
    contactInfo: 'a[href*="/overlay/contact-info/"], .pv-contact-info__link',
    email: '.pv-contact-info__ci-container a[href^="mailto:"]',
    phone: '.pv-contact-info__ci-container span[dir="ltr"]',
    connectedBadge: '.pv-top-card--connection-banner, .connection-banner',
    connectButton: 'button[aria-label*="Connect"], .pv-top-card__connect-button',
    messageButton: 'button[aria-label*="Message"], .pv-top-card__message-button',
    moreButton: 'button[aria-label*="More"], .pv-top-card__more-button',
    followButton: 'button[aria-label*="Follow"], .follow-button',
  },

  messaging: {
    messagingUrl: '/messaging/',
    conversationsList: '.msg-conversations-container, .msg-conversation-list',
    conversationItem: '.msg-conversation-listitem, .msg-conversation-card',
    newMessageButton: 'button[aria-label*="New message"], .msg-composer-button',
    recipientInput: 'input[aria-label*="Type a name"], .msg-connections-typeahead__text-input',
    messageTextarea: 'div[role="textbox"][contenteditable="true"], .msg-form__contenteditable',
    sendButton: 'button[aria-label*="Send"], .msg-form__send-button',
    messageBubble: '.msg-s-message-list__event, .msg-s-event-listitem',
    myMessage: '.msg-s-message-list__event--mine, .msg-s-event-listitem--mine',
    theirMessage: '.msg-s-message-list__event--theirs, .msg-s-event-listitem--theirs',
    connectionRequestNote: 'textarea[name="message"], .send-invite__custom-message',
    sendWithoutNote: 'button:has-text("Send without a note"), .send-invite__send-without-note',
    sendWithNote: 'button:has-text("Send"), .send-invite__send-button',
  },

  company: {
    companyUrl: '/company/',
    employeesTab: 'a[href*="/people/"], a[data-test-people-tab]',
    jobsTab: 'a[href*="/jobs/"], a[data-test-jobs-tab]',
    lifeTab: 'a[href*="/life/"], a[data-test-life-tab]',
    insightsTab: 'a[href*="/insights/"], a[data-test-insights-tab]',
    employeeList: '.org-people-profile-card, .org-people__card',
    employeeName: '.org-people-profile-card__profile-title, .artdeco-entity-lockup__title',
    employeeTitle: '.org-people-profile-card__headline, .artdeco-entity-lockup__subtitle',
    employeeLocation: '.org-people-profile-card__location, .artdeco-entity-lockup__caption',
    employeeProfileLink: '.org-people-profile-card__profile-link, .artdeco-entity-lockup__title a',
    searchEmployeesInput: 'input[placeholder*="Search people"], .org-people__search-input',
    filterByTitle: 'button[aria-label*="Title"], .org-people__title-filter',
    filterByLocation: 'button[aria-label*="Location"], .org-people__location-filter',
    loadMore: 'button:has-text("Show more"), .org-people__load-more',
  },

  notifications: {
    notificationsUrl: '/notifications/',
    notificationList: '.notifications-list, .nt-card-list',
    notificationItem: '.nt-card, .notification-item',
    notificationText: '.nt-card__text, .notification-text',
    notificationTime: '.nt-card__time, .notification-time',
    markAllRead: 'button:has-text("Mark all as read"), .mark-all-read',
  },

  captcha: {
    challenge: '#captcha-challenge, .captcha-container, iframe[src*="captcha"]',
    audioButton: 'button[aria-label*="Audio"], .captcha-audio-button',
    imageButton: 'button[aria-label*="Image"], .captcha-image-button',
    inputField: '#captcha-response, input[name="captcha"]',
    submitButton: 'button[type="submit"][form*="captcha"], .captcha-submit',
    refreshButton: 'button[aria-label*="Refresh"], .captcha-refresh',
    helpButton: 'button[aria-label*="Help"], .captcha-help',
  },

  toasts: {
    container: '.artdeco-toasts, .toast-container',
    toast: '.artdeco-toast-item, .toast',
    success: '.artdeco-toast-item--success, .toast--success',
    error: '.artdeco-toast-item--error, .toast--error',
    warning: '.artdeco-toast-item--warning, .toast--warning',
    info: '.artdeco-toast-item--info, .toast--info',
    message: '.artdeco-toast-item__message, .toast-message',
    dismiss: '.artdeco-toast-item__dismiss, .toast-dismiss',
  },

  common: {
    button: 'button, .artdeco-button',
    primaryButton: '.artdeco-button--primary',
    secondaryButton: '.artdeco-button--secondary',
    tertiaryButton: '.artdeco-button--tertiary',
    dropdown: '.artdeco-dropdown, [role="combobox"]',
    dropdownTrigger: '.artdeco-dropdown__trigger, button[aria-haspopup="listbox"]',
    dropdownContent: '.artdeco-dropdown__content, [role="listbox"]',
    dropdownItem: '.artdeco-dropdown__item, [role="option"]',
    modal: '.artdeco-modal, [role="dialog"]',
    modalHeader: '.artdeco-modal__header',
    modalContent: '.artdeco-modal__content',
    modalFooter: '.artdeco-modal__footer',
    input: 'input, textarea, select',
    label: 'label',
    errorText: '.artdeco-inline-feedback--error, .error-text',
    loadingSpinner: '.artdeco-spinner, .spinner',
    tooltip: '.artdeco-tooltip, [role="tooltip"]',
    tabList: '[role="tablist"], .artdeco-tabs',
    tab: '[role="tab"], .artdeco-tab',
    tabPanel: '[role="tabpanel"], .artdeco-tabpanel',
  },
};

export type LinkedInSelectors = typeof linkedinSelectors;